package inspector

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// ==== Rule test code start ====
func TestRuleSQLE00051(t *testing.T) {
	ruleName := SQLE00051
	type testCase struct {
		desc          string
		sql           string
		expectResults []*testResults
		expectError   bool
		mockDesc      string
		mockRows      string
		mockSQL       string
	}

	//===== test cases =====
	tests := []testCase{
		// CREATE 类语句
		{
			desc:          "case 1: 创建表使用GENERATED ALWAYS",
			sql:           "CREATE TABLE test_tb_1 (id BIGINT GENERATED ALWAYS AS IDENTITY, name VARCHAR(255));",
			expectResults: []*testResults{newTestResults().add(ruleName)},
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 2: 创建表使用GENERATED BY DEFAULT",
			sql:           "CREATE TABLE test_tb_2 (id BIGINT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(255));",
			expectResults: []*testResults{newTestResults().add(ruleName)},
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 3: 创建表不使用自增属性",
			sql:           "CREATE TABLE test_tb_3 (id BIGINT, name VARCHAR(255));",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 4: 创建表使用bigserial",
			sql:           "CREATE TABLE test_tb_4 (id BIGINT DEFAULT bigserial, name VARCHAR(255));",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 5: 创建表使用serial",
			sql:           "CREATE TABLE test_tb_5 (id SERIAL, name VARCHAR(255));",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		// ALTER TABLE 类语句
		{
			desc:          "case 6: 添加列使用GENERATED ALWAYS",
			sql:           "ALTER TABLE exist_tb_1 ADD COLUMN new_id BIGINT GENERATED ALWAYS AS IDENTITY;",
			expectResults: []*testResults{newTestResults().add(ruleName)},
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 7: 添加列使用GENERATED BY DEFAULT",
			sql:           "ALTER TABLE exist_tb_2 ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;",
			expectResults: []*testResults{newTestResults().add(ruleName)},
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 8: 添加列不使用自增属性",
			sql:           "ALTER TABLE exist_tb_1 ADD COLUMN new_id BIGINT;",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 9: 添加列使用bigserial",
			sql:           "ALTER TABLE exist_tb_1 ADD COLUMN new_id BIGINT DEFAULT bigserial;",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 10: 添加列使用serial",
			sql:           "ALTER TABLE exist_tb_1 ADD COLUMN new_id SERIAL;",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		// 新增示例 - CREATE 类语句
		{
			desc:          "case 11: 创建表使用GENERATED ALWAYS",
			sql:           "CREATE TABLE exist_tb_6 (id BIGINT GENERATED ALWAYS AS IDENTITY, name VARCHAR(255));",
			expectResults: []*testResults{newTestResults().add(ruleName)},
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 12: 创建表使用GENERATED BY DEFAULT",
			sql:           "CREATE TABLE exist_tb_7 (id BIGINT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(255));",
			expectResults: []*testResults{newTestResults().add(ruleName)},
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 13: 创建表不使用自增属性",
			sql:           "CREATE TABLE exist_tb_8 (id BIGINT, name VARCHAR(255));",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 14: 创建表使用bigserial",
			sql:           "CREATE TABLE exist_tb_19 (id BIGINT DEFAULT bigserial, name VARCHAR(255));",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 15: 创建表使用serial",
			sql:           "CREATE TABLE exist_tb_10 (id SERIAL, name VARCHAR(255));",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		// 新增示例 - ALTER TABLE 类语句
		{
			desc:          "case 16: 添加列使用GENERATED ALWAYS",
			sql:           "ALTER TABLE exist_tb_3 ADD COLUMN new_id BIGINT GENERATED ALWAYS AS IDENTITY;",
			expectResults: []*testResults{newTestResults().add(ruleName)},
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 17: 添加列使用GENERATED BY DEFAULT",
			sql:           "ALTER TABLE exist_tb_3 ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;",
			expectResults: []*testResults{newTestResults().add(ruleName)},
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 18: 添加列不使用自增属性",
			sql:           "ALTER TABLE exist_tb_3 ADD COLUMN new_id BIGINT;",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 19: 添加列使用bigserial",
			sql:           "ALTER TABLE exist_tb_3 ADD COLUMN new_id BIGINT DEFAULT bigserial;",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
		{
			desc:          "case 20: 添加列使用serial",
			sql:           "ALTER TABLE exist_tb_3 ADD COLUMN new_id SERIAL;",
			expectResults: _RuleAuditPassResults,
			expectError:   false,
			mockDesc:      "",
		},
	}

	for _, test := range tests {
		t.Run(test.desc, func(t *testing.T) {
			d, ctx := setupForRuleGeneral(t, ruleName, _DefaultParams)
			result, err := d.Audit(ctx, []string{test.sql})

			if test.expectError {
				assert.Error(t, err, test.desc)
			} else {
				assert.NoError(t, err, test.desc)
				assertRuleResult(t, test.desc, test.sql, test.expectResults, result)
			}
		})
	}
}

// ==== Rule test code end ====
