package inspector

import (
	"context"

	parser "actiontech.cloud/sqle/pg_query_go/v5"
	driverV2 "github.com/actiontech/sqle/sqle/driver/v2"
	"github.com/pkg/errors"
)

const (
	SQLE00051 = "SQLE00051"
)

func init() {
	rh := RuleHandler{
		Rule: driverV2.Rule{
			Name:       SQLE00051,
			Desc:       "禁止使用GENERATED ALWAYS类型自增属性",
			Annotation: "后期维护相对不便，过于依赖数据库自增机制达到全局唯一，不易拆分，容易造成主键冲突。特别是分布式环境下，自增主键容易引起数据分布不均衡、并发写入问题和主键冲突等问题。",
			Level:      driverV2.RuleLevelWarn,
			Category:   RuleTypeSuggestion,
			Params:     nil,
		},
		Message:              "禁止使用GENERATED ALWAYS类型自增属性",
		RawSQLHandler:        RuleSQLE00051,
		AllowOffline:         true,
		NotAllowOfflineStmts: nil,
	}
	RuleHandlers = append(RuleHandlers, rh)
	RuleHandlerMap[rh.Rule.Name] = rh
}

/*
==== Prompt start ====
在 TBase(PostgreSQL的分布式版本) 中，您应该检查 SQL 是否违反了规则(SQLE00051): "在 TBase 中，禁止使用GENERATED ALWAYS类型自增属性."
您应遵循以下逻辑：
1. 对于"CREATE TABLE ... "语句，检查以下条件，如果有任意一个条件满足，则报告违反规则：
    1. 该表有一个列定义为 generated always as identity 或者 generated by default as identity。
2. 对于"ALTER TABLE ... ADD ..."语句，进行与上述相同的检查。
==== Prompt end ====
*/

// ==== Rule code start ====
func RuleSQLE00051(ctx context.Context, rule *driverV2.Rule, sql string, nextSQL []string) (string, error) {
	node, err := sqlParserFuncV2(sql)
	if err != nil {
		return "", errors.Wrap(err, "parse sql")
	}

	// 检查表定义中的列是否违反规则
	checkTableColumns := func(tableElts []*parser.Node) bool {
		for _, elt := range tableElts {
			// 检查是否定义为 generated always as identity 或者 generated by default as identity
			if utilIsColumnHasConstraint(elt, parser.ConstrType_CONSTR_IDENTITY) {
				return true
			}
		}
		return false
	}

	// 检查 ALTER TABLE 语句中的列是否违反规则
	checkAlterTableColumns := func(cmds []*parser.AlterTableCmd) bool {
		for _, cmd := range cmds {
			// 检查是否定义为 generated always as identity 或者 generated by default as identity
			if utilIsColumnHasConstraint(cmd.Def, parser.ConstrType_CONSTR_IDENTITY) {
				return true
			}
		}
		return false
	}

	// 主逻辑：根据不同的 SQL 类型执行相应的检查
	switch stmt := node.GetStmt().GetNode().(type) {
	case *parser.Node_CreateStmt:
		// "CREATE TABLE ..." 语句
		if checkTableColumns(stmt.CreateStmt.TableElts) {
			return RuleHandlerMap[rule.Name].Message, nil
		}
	case *parser.Node_AlterTableStmt:
		// "ALTER TABLE ... ADD ..." 语句
		if checkAlterTableColumns(utilGetAlterTableCommandsByTypes(stmt.AlterTableStmt, parser.AlterTableType_AT_AddColumn)) {
			return RuleHandlerMap[rule.Name].Message, nil
		}
		if checkAlterTableColumns(utilGetAlterTableCommandsByTypes(stmt.AlterTableStmt, parser.AlterTableType_AT_AddConstraint)) {
			return RuleHandlerMap[rule.Name].Message, nil
		}
		// "ALTER TABLE ... ALTER ..." 语句
		if checkAlterTableColumns(utilGetAlterTableCommandsByTypes(stmt.AlterTableStmt, parser.AlterTableType_AT_AlterColumnType)) {
			return RuleHandlerMap[rule.Name].Message, nil
		}
	}

	return "", nil
}

// ==== Rule code end ====
